apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: python-script-controller-crd
rules:
- apiGroups: ["learn-k8s.com"]
  resources: ["python-script-containers"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch", "update"]