apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: python-script-controller-crd-binding
subjects:
- kind: ServiceAccount
  name: python-script-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: python-script-controller-crd
  apiGroup: rbac.authorization.k8s.io