apiVersion: v1
kind: Service
metadata:
  name: controller-flask-app
spec:
  type: NodePort
  selector:
    app: controller-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000